---
# This role creates a collectd environment for logging to graphite

- name: install collectd
  apt: name={{ item }} state=present
  with_items: 
    - collectd

- name: install collectd config
  copy: src=collectd.conf 
        dest=/etc/collectd/collectd.conf
  notify: restart collectd
