---
# This playbook deploys the whole application stack in this site.  

- hosts: ec2
  user: ubuntu
  sudo_user: root
  sudo: yes
  roles:
  - common
  - collectd
  - nginx
  handlers: 
        - name: restart collectd
          service: name=collectd state=restarted

- hosts: digitalocean
  user: root
  roles:
  - common
  - collectd
  - nginx
  handlers: 
        - name: restart collectd
          service: name=collectd state=restarted

- hosts: gatling
  user: mike
  roles:
  - gatling
  handlers: 
        - name: restart nginx
          service: name=nginx state=restarted

- hosts: webservers
  user: myapp
  roles:
  - app_setup

- hosts: webservers
  user: mike
  sudo: yes
  roles:
  - capaplan
  handlers: 
        - name: restart nginx
          service: name=nginx state=restarted


