---
# This playbook deploys the whole application stack in this site.  

- hosts: ec2
  user: ubuntu
  sudo_user: root
  sudo: yes
  roles:
  - common

- hosts: digitalocean
  user: root
  roles:
  - common

# Configure and deploy database servers.
- hosts: dbservers
  user: root
  roles:

- hosts: webservers
  user: mike
  sudo: yes

  roles:
  - capaplan

# Configure and deploy the load balancer(s).
- hosts: lbservers
  user: root
  roles:

